#!/usr/bin/env ruby

require_relative 'lib/pizzabot'

def get_instructions(instruction_string)
  return if instruction_string.nil?

  instructions_array = instruction_string.split(' ', 2)
  neighborhood_dimensions = instructions_array[0]
  delivery_locations = instructions_array[1]

  return "Incorrect Input" if neighborhood_dimensions.nil? || delivery_locations.nil?

  instructions = PizzaBot.new(
                   neighborhood: neighborhood_dimensions,
                   locations: delivery_locations
                 ).delivery_instructions
end

puts get_instructions(ARGV[0])
